feat: Select multiple controls using rectangle area
adilek/jirtdan pull request #29
Opened 2017-06-22 21:02 UTC by rzaaeeff

2017-06-22 21:04 UTC, rzaaeeff commented
@adilek please, check this out.

2017-06-22 21:06 UTC, rzaaeeff commented
![](https://github.trello.services/images/mini-trello-icon.png) [Select several components using rectangle area.](https://trello.com/c/LswWE9Fj/1-select-several-components-using-rectangle-area)

2017-06-22 21:07 UTC, rzaaeeff commented
![](https://github.trello.services/images/mini-trello-icon.png) [Select several components using rectangle area.](https://trello.com/c/LswWE9Fj/1-select-several-components-using-rectangle-area)

2017-06-23 04:28 UTC, adilek requested changes

2017-06-23 04:28 UTC, adilek commented on app/app/Board.js
>      onMouseUp(event) {
In my opinion you should select/unselect during mouse move not mouseUp.
Just a UX example select several files in Windows explorer. The files are being selected/unselectd on mousemove event. What do you think?

2017-06-23 07:28 UTC, rzaaeeff commented
@adilek I think it would be cool, too.

I've tried it, it slows drawing process (frame rate drops) when there are many controls in board.

2017-06-23 07:55 UTC, adilek commented
@rzaaeeff, 
Thanks for clarification. I think lets make with mouse move even there are framedrops or other performance issues. Lets think about it later. First need to focus on UX then performance in my opinion.

2017-06-23 08:19 UTC, adilek approved these changes

2017-06-23 08:19 UTC, merged

2017-06-23 08:19 UTC, rzaaeeff commented
@adilek thank you.